### ISSUE TITLE
No Payment Needed Checkout (OCC-52)

### ISSUE THREAD

**Issue by jeffolmstead** [OrchardCMS/OrchardCore.Commerce#13]
Implementation should allow a user to checkout without a payment if their shopping cart totals no cost. 

[Jira issue](https://lombiq.atlassian.net/browse/OCC-52)

**Comment by porgabi** [comment]
@DAud-IcI Any more details on how this should work?

**Comment by DAud-IcI** [comment]
If your cart only have free items and the final total is zero, then the payment part (e.g. card details entry and the callback to Stripe's API) should be skipped. So that's some change in the front end and the back end too.
Also verify that Stripe can correctly handle an order with a mixture of free and priced products.
