### ISSUE TITLE
Anonymous checkout (OCC-79)

### ISSUE THREAD

**Issue by khoshroomahdi** [OrchardCMS/OrchardCore.Commerce#19]
it would be possible to sell digital file such book or files without sign up and required email address. and download after purchase from browser.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-79)

**Comment by Skrypt** [comment]
Anonymous checkout

**Comment by khoshroomahdi** [comment]
Exactly

**Comment by bleroy** [comment]
Changed the title to reflect that. Thanks!

**Comment by bleroy** [comment]
Changed the title to reflect this. Thanks!

**Comment by bleroy** [comment]
Understood, thanks!

**Comment by Piedone** [comment]
To confirm, the checkout currently (not talking about digital good purchases that's not available yet) can be anonymous, no, @DAud-IcI?

**Comment by DAud-IcI** [comment]
Since #154 it is possible to grant the "Ability to checkout" permission to the Anonymous role. Since  #155 you can provide all necessary details on the checkout screen including email and billing address. (the shipping address fields are technically required, but you should be able to hide them via placement) After successful checkout you are redirected to the Order's display page (as of #156) so you can include a download URL there using a link field or custom templates. These three work together, I have just confirmed.

Technically nothing stops you from leaving the email field empty during checkout. It's pre-populated for authenticated users so it's no concern for the regular use-case. If you want your store to be anonymous-only, you can hide the field via placement configuration. On the flip side if the user provides an email address you can send out the download URL using workflows (Order Content Published trigger and Email task). Anything else you need for digital goods should be doable using normal OC features and it's probably very specific to your content delivery backend, which would likely fall out of OCC's scope. But if you have a specific request feel free to open a new issue.
