### ISSUE TITLE
Product Promotions: Discount with DiscountPart (OCC-127)

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore.Commerce#255]
Hi, thanks for implementing OrchardCore Commerce!

I have just cloned the actual repo and did some tests. Regarding the discounts:
In Nwazet commerce, there has been a content type Discount with a DiscountPart. The concept was having different discounts with "rules" when they apply - see screenshot:

![image](https://user-images.githubusercontent.com/1379660/213266603-134f39c4-068c-41d3-9c64-bace644e9633.png)

I have used this to apply discount depending on user role.

In the current implemtation, it seems that the DiscountPart is attached to the product.
Are the any plans to change that like it previously was in NwazetCommerce?
If yes, is there any timeline?
If no, how could a role-based discount be integrated in the currenct concept/implemtation?

Sorry for cross-posting - I have already commented  on https://github.com/OrchardCMS/OrchardCore.Commerce/issues/9 but not sure if this is still alive since it's from 2018.

Thanks, Dieter

[Jira issue](https://lombiq.atlassian.net/browse/OCC-127)

**Comment by DAud-IcI** [comment]
Hi Dieter,

that's a good idea. We didn't think of this yet and nobody has brought it up before. Note that we aren't trying to meticulously copy Nwazet (mainly because we don't know which features of it people actually use). We only use specific parts as reference when someone points to them.

Annoyingly enough, OC has built-in content picker and user picker fields, but no role picker field. Otherwise this would be really easy to implement by adjusting `DiscountProvider.IsApplicableAsync()`. I will ask around.

**Comment by dpomt** [comment]
Hi David,

thank's for your reply. 
Do you have any ideas how non-product specific role-based discounts could be implemented without implementing a discount content part? 
Of course a role-base discount can be added to all available products, but guess this is not the way it should be handled.

Thanks,
Dieter

**Comment by DAud-IcI** [comment]
To make sure that I understand correctly: do you want the same functionality as DiscountPart but it should apply to every product if the user has a certain role? (i.e. a securable discount content item) Or are you looking for something more specific?

**Comment by dpomt** [comment]
Yes, that's exactly what I need.
