### ISSUE TITLE
Creating a new user directly in the Users menu fails if no address is given (OCC-150)

### ISSUE THREAD

**Issue by wAsnk** [OrchardCMS/OrchardCore.Commerce#285]
### Describe the bug

Creating a new user in the admin requires you to fill user address, but if you don't then no error message is given and simply there is nothing happening when clicking on save. Also "Shipping Address and Billing Address are the same" checkbox is not working on the User Addresses tab.

### To Reproduce

1. Go to /Admin/Users
2. Create new user
3. Do not fill data on User Addresses tab
4. Fill required data on Content tab
5. Click save, nothing happens, no error
6. Fill required data on User Addresses tab
7. Notice "Shipping Address and Billing Address are the same" is not working
8. Click on save, user is saved

### Expected behavior

Either it should not be required to fill the User Addresses data at all while creating a new User via the admin or a validation error should appear when it's not filled.

If this tab won't be there then fixing the checkbox is not needed.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-150)

**Comment by DAud-IcI** [comment]
> Click save, nothing happens, no error

This is not specific to OCC, it's a problem with OC's built-in client side form validation for content fields (I'm not sure, may be using [jQuery Unobtrusive Validation](https://github.com/aspnet/jquery-validation-unobtrusive)). It doesn't show the error if the affected field is invisible because it's on a different tab. If you go to the User Addresses tab and click Publish without filling the fieds it actually shows the error using the standard client side tooltip.
