### ISSUE TITLE
PriceVariantsPart doesn't support InventoryPart (OCC-163)

### ISSUE THREAD

**Issue by DAud-IcI** [OrchardCMS/OrchardCore.Commerce#302]
### Describe the bug

It should track the amount for each variant separately.

### To Reproduce

1. Create a content type with PriceVariantsPart and InventoryPart
2. Buy any variant.
3. The single stock number reduces.

### Expected behavior

Should be multiple numbers for each variant. Somehow.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-163)

**Comment by MatteoPiovanelli-Laser** [comment]
May I point you to our Nwazet.ProductCombinations feature in our O1 fork of Nwazet: https://github.com/LaserSrl/Nwazet.Commerce/tree/Laser

The way we did it is basically:

- you add a ProductCombinationPart to your Product
  - This generates a "secondary" ContentType
- In the editor for that, you have UI to generate product combinations, that will be contents of the "secondary" type, connected to the product you are starting from.
  - Some properties of the product are copied over, and can be personalized in each combination. (this is controlled by providers)
  - in the editor UI for the "main" product you have a table of all its combinations.
-  The combinations don't have their own frontend view, but rather redirect to the one for the main product.
- in the frontend for the main product, you are actually selecting the combination product to add to your cart.
  - Thanks to jquery trickery, selecting different combinations, changes frontend UI stuff: for example, the price/discount applied, or the picture displayed.
  
Frontend example from one of our demos (can't actually buy anything from there): https://full-demo.mykrake.com/it/prodotto/pantalone-da-lavoro-uomo

The "combinations" contentType is lighter than the full product, because often you don't have to repeat every part and filed in it.

**Comment by porgabi** [comment]
I was thinking of two approaches here:

1. Adapt InventoryPart to specifically PriceVariantsPart's needs, i.e. add a few new properties to it that would handle the multiple inventories. This would involve adding new properties for minimum and maximum order quantities as well.
2. Change the way InventoryPart stores inventory by making it a dictionary, allowing it to hold multiple separate inventories. The minimum and maximum order quantities properties would also need to change in a similar manner.

Option 1 sounds simpler, but as it'd be specifically made for PriceVariantsPart, it might not help with a similar problem in the future.
Option 2 seems more future-proof, if my line of thought is correct.

What do you think, @DAud-IcI? If you have a better idea than these, I don't insist on going with any of the above.

**Comment by DAud-IcI** [comment]
@porgabi Option 2 sounds like the way to go. At this level of complexity specific fixes just tend to backfire.

The dictionary key should be the product full SKU, so the base SKU and `ShoppingCartItem.GetVariantKeyFromAttributes(attributes)` separated by a dash, if it's not null or empty. (I'd make a method for that in `IProductService`, e.g. `string GetOrderFullSku(ShoppingCartItem item, ProductPart productPart)` to reuse and DRY some code already in `PriceVariantProvider.AddPriceToShoppingCartItem`)

**Comment by porgabi** [comment]
@DAud-IcI How should minimum and maximum order quantities work for Price Variant Products? Should it be possible to specify these values per variant, or would it be better to have one value affect all variants?
