### ISSUE TITLE
Products listing page (OCC-185)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#343]
The default experience with the AutoSetup is nice but it could be interesting to have an example of a page that lists products (it should even be the homepage, as expected on an Ecommerce site).

Instead, I needed to go to the admin to list the content items and click on View for one of the products.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-185)

**Comment by agriffard** [comment]
Thank you, that is a start.

Suggestion: Some parts should only be visible on Details, not on Summary, like Quantity/Add to cart, but we know this is also the purpose of a dedicated theme.

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/703248/df261ab7-f0a4-4737-bbae-1456552473db)

**Comment by DAud-IcI** [comment]
I don't think we should do such small adjustments, because OCC is was never meant to be a turn-key solution. When it comes to placement and visibility I prefer to keep everything as close to stock as possible. Commerce developers can make those adjustments on their own and shouldn't have to fight against the use cases we anticipate if it doesn't match their vision.
