### ISSUE TITLE
Don't require login to browse the products in the autosetup recipe (OCC-190)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#349]
If you are logged in, the home url redirects to the login.
You should be able to access it anonymously.

This is currently a `Page` content type that only has a TitlePart and an AutoroutePart.

You have to provide some ways to list products (Widgets on Home Layer or LiquidPart with query).

[Jira issue](https://lombiq.atlassian.net/browse/OCC-190)

**Comment by agriffard** [comment]
I guess you started a PR to use a ListPart here: #346.

**Comment by DAud-IcI** [comment]
Since the listing on the home page has already been handled in #343 (OCC-185), what's left to do here is to add permissions to the development setup recipe. It's possibly enough to just move the roles step from _OrchardCore.Commerce.Development.Tests.Setup.recipe.json_ to _OrchardCore.Commerce.Development.Setup.recipe.json_. I've updated the title accordingly.
