### ISSUE TITLE
User informations (OCC-191)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#350]
Users should be able to edit their informations (addresses, details) and consult their orders from the Front end.

[Jira issue](https://lombiq.atlassian.net/browse/OCC-191)

**Comment by agriffard** [comment]
Found `/user/addresses` which I guess is the url to manage your addresses.

**Comment by DAud-IcI** [comment]
Users can already edit their addresses and some other details on the front end, see [here](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/Modules/OrchardCore.Commerce/Controllers/UserController.cs#L66). These may be added to a menu or something, but if so that should be done in the theme (#300)
