### ISSUE TITLE
Catalog navigation and Search (OCC-192)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#351]
One of the most important feature of an ecommerce site is to allow to find a specific product easily.

You should be able to organize your products by hierarchical categories (i.e Taxonomies) in order to navigate in the catalog (Autoroute parent path, Breadcrumbs, ...).

A listing of products have to offer multiple sorts (Lower to higher price, Higher to lower price, most recent, featured, ...).

It would be also really useful to provide an advanced faceted search (Filter by multiple criteria: Price range, variants, Brand)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-192)

**Comment by barthamark** [comment]
My initial thought was to utilize the Lists feature and use ListPart somehow. However, it appears that the querying logic behind `ListPart` is not extensible in the sense that we can't really tap into the query to filter by different attributes. To address this, I'm considering creating a ProductListPart that initiates a Product query. An IProductFilterProvider could then tap into this for filtering. For example, a filter provider would check for the presence of a relevant query string and add the criteria accordingly. As for adding the query string, we can create a few built-in widgets for this, but essentially, it's up to the developer. Please let me know your thoughts; otherwise, I'll go ahead and build the infrastructure for this.

**Comment by DAud-IcI** [comment]
That's a good approach. Create a context for the filter parameters, the query object, and the result too (from previous experience I'm certain eventually we'll need both online and offline filtering) so we can chain multiple providers. We'd probably need separate index providers for each kind of filterable criteria and then they can be joined to the query by the filter providers.

Price is a huge question, because people often want the ability to sort by price, but price can vary based on the user, especially with discounts, so I'm not sure how well that can be indexed.

I think the filter widget can be made a followup issue, so for now it's enough if the query string s work.

**Comment by barthamark** [comment]
In my opinion it'd make sense to create at least a few widgets to make the feature actually usable. I was thinking about a filter for the product attributes and maybe an order by widget (order by price and title). At least something basic that can be extended in a separate issue based on feedback.

**Comment by DAud-IcI** [comment]
Most important is to have a title/fulltext search widget. Every other widget beyond that is a bonus.

For the product attributes, eventually I'd like to have the filter provider populate a list of models based on the field settings, so we can automatically generate something like the sidebar you see on Amazon or Árukereső. That would be a single widget with one shape for each filter so they can be shape-overridden by type or by name if needed. This is why I wrote that it can be a followup issue. If you want to have something simpler as a temporary solution, that's fine.

I think "order by" should be part of the product list part rather than a widget. After all, it's always above/below the product list, usually right next to the pager. (e.g. both pager and sorting could be separate shapes displayed by the part's driver)
Either way, the available "order by" options should be populated by the filter providers to keep it modular.
