### ISSUE TITLE
Use interface to abstract all of kinds of parts

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore.Commerce#37]
inside class PriceProvider : IPriceProvider

how can I change
`var pricePart = item.Product.As<PricePart>();`
to  
`var pricePart = item.Product.As<IPrice>();`

**Comment by infofromca** [comment]
maybe use <T> ?

**Comment by bleroy** [comment]
Well, the design here was that this specific price provider was specialized for the price part. If you're using a different kind of part that implements its price differently, you'd build another price provider that goes with it. However, since nothing this provider does depends on anything else than `IPrice`, I think you're right that we could refactor this to look for any part that implements `IPrice` and get the price from that.

**Comment by bleroy** [comment]
Wait, no, we can't. There's no way in Orchard Core to get a part from an item without knowing their actual type. An interface won't work. So no, this is unfortunately not possible, and if you define your own implementation of `IPrice`, you'll have to also build a new implementation of `IPriceProvider`.
Please re-open if I missed something.
