### ISSUE TITLE
make class Address partial (OCC-205)

### ISSUE THREAD

**Issue by dpomt** [OrchardCMS/OrchardCore.Commerce#386]
Hi,

need additonal fields in shipping and billing address.
Would it be possible to make the "Address" class a partial class to let me extend the class?

And how could AddressFormatter be overwritten to take care of additional fields in the class extension?

Thanks
Dieter

[Jira issue](https://lombiq.atlassian.net/browse/OCC-205)

**Comment by sarahelsaig** [comment]
Hi Dieter,

in C# [all partial-type definitions meant to be parts of the same type must be defined in the same assembly](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods), so I don't think the language allows what you are trying to do. Historically, `partial` exists to merge together generated code (like WinForms or EF) with custom source. It's not an extensibility feature.

Why do you want to add these fields to the `Address` class?

**Comment by dpomt** [comment]
Hello Sára,

thanks for your reply. I was not aware that partial is limited that way.

For the address, I need to handle additional fields like title, given name and family name (one common name field is not sufficient). 
Additionally, I would like to store an additional tax number and a customer number as part of the the billing address.

I thought best way to handle this would be to extend the address class and provide custom implemtations of AddressFieldEditor.cshtml and Checkout.cshtml.


Any ideas how I could achieve the extension?

Thanks.
Dieter

**Comment by sarahelsaig** [comment]
You can create a custom content part with the additional information as content fields and then attach it to the Order content type. 

Then override the Checkout shape by copying the [Checkout.cshtml](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/582887b59425653abcee8b21712bcea5ef28d035/src/Modules/OrchardCore.Commerce/Views/Checkout.cshtml) into your module or theme and customizing it to include editors for the new fields. The input names have to match what you'd see in the content item editor (e.g. `name="AdditionalInformationPart_CustomerNumber_Text"` if you create Additional Information content part with a text field called Customer Number). This was the display manager will update your fields include it during order creation. Note that even if extending `Address` was possible you'd still have to do this (and also replace the `AddressFieldDisplayDriver`) to map the additional information to the front end.

**Comment by dpomt** [comment]
Thanks, I will try that.

I have seen that ShippingAddress and BillingAddress are stored at the user using UserAddressesPart.
If I would like to store the content of the AdditionalInformationPart also at the user, would I have to create a UserAdditionalInformationPart as it is done with UserAddressesPart?

**Comment by sarahelsaig** [comment]
You should be able to reuse the same part, just create a content type with the [CustomUserSettings](https://docs.orchardcore.net/en/main/docs/reference/modules/Users/CustomUserSettings/) stereotype in migration like:
```csharp
_contentDefinitionManager.AlterTypeDefinition("UserAdditionalInformation", builder => builder
    .Stereotype("CustomUserSettings")
    .WithPart(nameof(AdditionalInformationPart)));
```

**Comment by dpomt** [comment]
Thanks, will try it.

Concerning the address class:
It would be great if the "Name" would be splitted in three parts 
- title (name prefix)
- given name (first name)
- family name (last name/surename)

It would be much easier for formatting the address and the UI form in checkout view than putting them in a additional custom content part.
What do you think about it?

I am ok with the additional content part for the further fields like customer ID.

**Comment by sarahelsaig** [comment]
The split you proposed would not work well in the English sphere. Especially in the USA, where having a middle name is so common sometimes people without one [had to use placeholder](https://en.wikipedia.org/wiki/Middle_name#:~:text=The%20abbreviation%20%22N.M.N.%22%20(no%20middle%20name)%20or%20%22N.M.I.%22%20(no%20middle%20initial)%2C%20with%20or%20without%20periods%2C%20is%20sometimes%20used%20in%20formal%20documents%20in%20the%20United%20States%2C%20where%20a%20middle%20initial%20or%20name%20is%20expected%20but%20the%20person%20does%20not%20have%20one) middle names in forms that require one. On the flip side, [some people officially don't have a last name](https://www.linkedin.com/pulse/i-dont-have-surname-simran-/).
There are more quirks. In Hungary where I live, the family name is the first name, not the last. Also sometimes the title is not a true prefix because other name parts can precede it. Here is an example using common names, "Kovácsné dr. Nagy Mária" (dr Mary Big, wife of Smith) is a doctor, while "dr. Kovácsné Nagy Mária" (Mary Big, wife of doctor Smith) may just be married to a doctor. Trying to represent all this in a form would give me an aneurysm with no real doctors in sight, but it's totally valid,
Once you have to serve an international audience [names are deceptively complex](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/). Our current implementation only makes the minimum assumptions that the customer has a name and that it can be represented using Unicode.

We could introduce a new property e.g. `IDictionary<string, string> NameParts`, and an extension point in `AddressFieldDisplayDriver` for a formatter that regenerates `Name` based on `NameParts` whenever they are updated. This way you can override the `AddressFieldEditor` shape to use specific entries in the dictionary for the input fields instead of the `Name` property. It wouldn't break compatibility or impose a locale-specific structure either. Does that make sense?

**Comment by dpomt** [comment]
Thanks for the clarification. I was not aware of the complexity.

My customer only sells in Germany and the ERP relys on the single name parts. Trying to split the name in the parts does not work well.
Your proposal with the NameParts dictionary would definitely help.

Would it also be possible to have an additional IDictionary<string, string> AdditionalFields? That would make it much more easy to also store additional fields like the customer number.

Thanks,
Dieter

**Comment by sarahelsaig** [comment]
> Would it also be possible to have an additional IDictionary<string, string> AdditionalFields?

Sure, why not.

> That would make it much more easy to also store additional fields like the customer number.

Do you need separate customer number for shipping and billing? If not, then I think my previous advice about attaching a new part to the Order content type still works better for this case. Also if the user has to log in before completing the order, then attaching the customer number to the User object (with a [`CustomUserSettings`](https://docs.orchardcore.net/en/main/docs/reference/modules/Users/CustomUserSettings/) content part) would be a better fit.

**Comment by dpomt** [comment]
It is the same number for shipping and billing. 
The user needs to login before completing the order, I will try to use a CustomUserSettings content part.

I will try and get back, will take some time.

Until then - wish you a Happy New Year.

**Comment by sarahelsaig** [comment]
Thanks, you too!
I've already started working on adding NameParts and AdditionalFields last week. I just forgot to assign myself here on GH.

**Comment by sarahelsaig** [comment]
@dpomt We've added this feature to the main branch. You can see an example by enabling the "Orchard Core Commerce - Western Name Parts" feature.

Also see [`WesternCommonNamePartsAddressUpdater`](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/d016f2ac6ce54fe41a058f02556663982ae01ac6/src/Libraries/OrchardCore.Commerce.AddressDataType/Services/WesternCommonNamePartsAddressUpdater.cs) and [AddressFieldEditor-WesternCommonNameParts.cshtml](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/d016f2ac6ce54fe41a058f02556663982ae01ac6/src/Modules/OrchardCore.Commerce.ContentFields/Views/AddressFieldEditor-WesternCommonNameParts.cshtml). Basically you can register an `IAddressUpdater` instance like `SomethingAdderssUpdater`. This will tell the driver how to update the `Address.Name` property from the `Address.NameParts` dictionary. Then you can override the `AddressFieldEditor` shape with the `AddressFieldEditor-Something` shape (so the name of the address updater service but the `AdderssUpdater` suffix can be omitted).

**Comment by dpomt** [comment]
@sarahelsaig 
Thanks so much. I have tested this and it works :)
