### ISSUE TITLE
Build NuGet and CloudSmith Packages (OCC-29)

### ISSUE THREAD

**Issue by agriffard** [OrchardCMS/OrchardCore.Commerce#42]
Will you create a `dev` branch at some point?

Then, is it possible to setup a CI (Travis, AppVeyor) in order to build the packages?

It would be great if `dev `packages could be uploaded to a MyGet feed and `master` to NuGet, as it is done in OC.

**Comment by bleroy** [comment]
I'd add to this configuring GitHub actions to build, package and test, rather than an external CI, if that's sufficient for our needs.

**Comment by DrewBrasher** [comment]
I will work on this.

**Comment by bleroy** [comment]
As far as I can tell, the CI workflow doesn't upload packages to MyGet and NuGet as requested by @agriffard .

**Comment by Skrypt** [comment]
Should we push to the same Cloudsmith account as Orchard Core or we should ask you Bertrand to create a separate account for MyGet, Nuget and CloudSmith?

**Comment by bleroy** [comment]
I'm puzzled: the project is not built as a single assembly.

Also, since I'm no longer the main maintainer of the project, it wouldn't make sense for me to open the accounts. The project is under the Orchard GitHub org, it seems like we should be able to do the same thing and use the same accounts as the main project, no?

**Comment by Skrypt** [comment]
You are right It is not a single assembly. We need to ask @sebastienros what he thinks about it.

**Comment by Skrypt** [comment]
Here is my confusion.

![image](https://user-images.githubusercontent.com/3228637/176259890-6ee5eb82-4eb3-4da9-9a4b-bbf9d09ea52a.png)

I created an OrchardCore.Commerce.Targets module so that I can reference it simply from my main web project. This way, it becomes a single required referenced assembly. Though, I did this to replicate also the Orchard Core project folder structure so that I can reuse the same Github workflows and VS Code launcher/tasks.

**Comment by DAud-IcI** [comment]
This can utilize our [reusable GitHub workflow for publishing to a NuGet feed](https://github.com/Lombiq/GitHub-Actions/blob/dev/.github/workflows/publish-nuget.yml). I don't think it's necessary to have a separate `dev` branch, pushing to `main` could trigger a publish for CloudSmith/MyGet and creating a release could trigger a publish for NuGet. That would be cleaner and I think we have all the pieces to make it happen.

@sebastienros what do you think, should it be under the Orchard Core CloudSmith account as Jasmin suggested?

**Comment by Piedone** [comment]
We can publish preview packages, i.e. packages after all `main` commits to Cloudsmith, under the OrchardCore account, and release packages to NuGet, under the Orchard account. I.e. the same as we do with OC.

**Comment by DAud-IcI** [comment]
@sebastienros could you please update the two secrets [here](https://github.com/OrchardCMS/OrchardCore.Commerce/settings/secrets/actions)? (`CLOUDSMITH_API_KEY` and `NUGET_API_KEY`; I have added the variables with only placeholder values.) Then we can start with this issue asap. Thanks.

**Comment by Piedone** [comment]
Before the first NuGet release, we should decide on the names of `AddressDataType` and `MoneyDataType`. I recommend just prefixing them with `OrchardCore.Commerce.`.

**Comment by DAud-IcI** [comment]
I agree. Even if they are meant to be generic, they will evolve alongside OCC so they should be together.
Anyone against this namespace change, please chime in.

**Comment by DAud-IcI** [comment]
> @sebastienros could you please update the two secrets [here](https://github.com/OrchardCMS/OrchardCore.Commerce/settings/secrets/actions)? (`CLOUDSMITH_API_KEY` and `NUGET_API_KEY`; I have added the variables with only placeholder values.) Then we can start with this issue asap. Thanks.

up

**Comment by Piedone** [comment]
Hmm, the (or some) keys are there, actually!

![image](https://user-images.githubusercontent.com/1976647/184725498-eabec904-be82-4d4b-9b35-e8b67a7b1952.png)

So Sebastien swooped in but forgot to tell?

(Before you ask, I have access to this settings page but not to the NuGet account, hence why I didn't do it in the first place.)

**Comment by Piedone** [comment]
Ah no, now I notice that Dávid you added placeholders.

**Comment by DAud-IcI** [comment]
Yup, these are just the empty variables I've set up, waiting for the values to be updated.
(you can see that the "days ago" is the same as [my previous comment](https://github.com/OrchardCMS/OrchardCore.Commerce/issues/42#issuecomment-1205102781))

**Comment by Piedone** [comment]
I remembered I actually have access to the Cloudsmith repo! So created and configured one: https://cloudsmith.io/~orchardcore/repos/commerce/packages/

However, to provide push access to it, a user's API key is needed. You can only use a user's single, personal API key to publish packages. The recommended way to do this is by creating a bot account just for this. I'd do that, but I need to store the credentials somewhere. Isn't there an Orchard LastPass, @sebastienros?

**Comment by DAud-IcI** [comment]
The `preview` repo seems to be using Sébastien's personal account so a technical user probably wasn't considered.
![image](https://user-images.githubusercontent.com/4007293/184877672-d1ab2cec-babf-4508-b9a0-313e259b67cf.png)
Can't we create a dedicated account using a Lombiq email address, at least for now? You wouldn't have to store the creds, since it won't be used for anything else. Then Sébastien & co can replace it with something else later if they want to.

**Comment by DAud-IcI** [comment]
btw I've already made the namespace changes and created the workflows in a branch. Didn't have the opportunity to test them in lieu of the API keys, but the NuGet workflow should be perfect as it's exactly the same we use to publish Lombiq's open source projects. The CloudSmith workflow required a non-trivial improvement in the parent action, because that would trigger on every `main` merge instead of a tag, but I'm optimistic and eager to test it.

**Comment by Piedone** [comment]
I've added Lombiq Bot to the Bots group (https://cloudsmith.io/orgs/orchardcore/teams/bots/members/) and configured the API key under Secrets.

**Comment by DAud-IcI** [comment]
Thanks. [It works for CloudSmith now.](https://cloudsmith.io/~orchardcore/repos/commerce/packages/)

However for now I could only test it by pushing a tag. (Looks like [`on.publish.branches = ["main"]` condition](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/issue/OCC-29/.github/workflows/publish-cloudsmith.yml#L3-L6) can only be triggered from the `main` branch? If so, that's perfectly logical. [OC is doing the same anyway](https://github.com/OrchardCMS/OrchardCore/blob/main/.github/workflows/preview_ci.yml#L8) so it should be fine) 

I'm still waiting for a NuGet key, then this can be reviewed.

**Comment by Piedone** [comment]
Yep, the branch trigger will only work if the workflow exists on that branch.

**Comment by sebastienros** [comment]
NUGET_API_KEY updated with same key as in OC

**Comment by DAud-IcI** [comment]
Thanks Sébastien, it works. https://www.nuget.org/packages/OrchardCore.Commerce
