### ISSUE TITLE
There are two exceptions in OrchardCore.Commerce 2.0 while building project : ArgumentException: Illegal characters in path (OCC-230)

### ISSUE THREAD

**Issue by effapp** [OrchardCMS/OrchardCore.Commerce#422]
### Describe the bug

There are two exceptions in OrchardCore.Commerce 2.0 while building project : ArgumentException: Illegal characters in path

### To Reproduce

1. Clone OrchardCore.Commerce 2.0 repository
2. Right click on 'OrchardCore.Commerce.Web' project and click on 'Build' menu in pop menus
3. Display ArgumentException: Illegal characters in path in console window
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51013754/45355e34-d6e5-4691-8fd3-de0c97c4bb53)

5.Right click on package.json of OrchardCore.Commerce.Web and click  on 'Task runner explorer' menu of pop menus
6.Double click on build of ask runner explorer and dispaly error:
npm ERR! explore It doesn't look like nodejs-extensions is installed. As follow figure:

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51013754/902eba77-9ab5-4fb6-8fab-92d4d7fea1e5)

### Screenshots

Project dependencies window display error: NPM->VisibilityMarker

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51013754/e717a466-c999-4ae9-8e92-d9edf76d92a4)

[Jira issue](https://lombiq.atlassian.net/browse/OCC-230)

**Comment by effapp** [comment]
Hi @sarahelsaig ,
There is a garbled code of path in output window:

[?25l[36m?[39m [1mThe modules directory at "F:\tests\oc\OrchardCore.Commerce\src\Modules\OrchardCore.Commerce.ContentFields\node_modules\.nx\node_modules" will be removed and reinstalled from scratch. Proceed?[22m [2m(Y/n)[22m

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51013754/74e0ad44-1ed1-4b37-99a9-694c1062856a)

**Comment by sarahelsaig** [comment]
I've looked into this [src/OrchardCore.Commerce.Web/package.json](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/OrchardCore.Commerce.Web/package.json) file and I don't think we even need it any more. All the other files added in the same commit have since been deleted. Could you delete it and see it that fixes your issue?

> There is a garbled code of path in output window

I don't think that's a problem, it just looks weird because the VS console can't understand terminal escape sequences.

**Comment by effapp** [comment]
> I've looked into this [src/OrchardCore.Commerce.Web/package.json](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/main/src/OrchardCore.Commerce.Web/package.json) file and I don't think we even need it any more. All the other files added in the same commit have since been deleted. Could you delete it and see it that fixes your issue?
> 
> > There is a garbled code of path in output window
> 
> I don't think that's a problem, it just looks weird because the VS console can't understand terminal escape sequences.

Hi @sarahelsaig ,
I have deleted src/OrchardCore.Commerce.Web/package.json file,but errors are same.

**Comment by effapp** [comment]
> It's not clear what's going on. Could you attach the whole build log? Using the structured _binlog_ format would be best, see [here](https://learn.microsoft.com/en-us/visualstudio/ide/msbuild-logs?view=vs-2022#capture-binary-logs-through-visual-studio).

Hi @sarahelsaig ,

The above exceptions are completely absent when I use following method to generate _binlog_ format logs

SET MSBUILDDEBUGENGINE=1
SET MSBUILDDEBUGPATH=d:\MSBuildReproLogs
"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" OrchardCore.Commerce.sln

Why?

**Comment by sarahelsaig** [comment]
Unfortunately I'm not sure since I could never reproduce it on my end. It may be the case of Visual Studio being weird. The compiler in VS behaves slightly differently form using the CLI tools  from .NET SDK, although in the past this only caused warnings for me, never a full build error. Perhaps this `MSBUILDDEBUGENGINE` flag forced it to use the SDK's `MSBuild.exe` under the hood.

In general our [tagged releases](https://github.com/OrchardCMS/OrchardCore.Commerce/releases) are guaranteed to succeffully build using the `dotnet` CLI, because that's what the script uses under the hood for publication. Even if you have no success with VS, this should always work:
```cmd
dotnet restore
dotnet build OrchardCore.Commerce.sln
```
