### ISSUE TITLE
Province  and Country should be required (OCC-299)

### ISSUE THREAD

**Issue by infofromca** [OrchardCMS/OrchardCore.Commerce#499]
### Describe the bug

otherwise, how the Tax can be applied?

### To Reproduce

1. Go to 'AddressFieldDisplayDriver'
```
  private static readonly Dictionary<string, Func<Address, string>> RequiredFields = new()
 {
     [nameof(Address.Name)] = address => address.Name,
     [nameof(Address.StreetAddress1)] = address => address.StreetAddress1,
     [nameof(Address.City)] = address => address.City,
 };
```

### Expected behavior
At least Province should be required

[Jira issue](https://lombiq.atlassian.net/browse/OCC-299)

**Comment by sarahelsaig** [comment]
Country/Region is not required, because there are stores that only sell in their own country. In that case country information is not relevant and it's logical to omit the country field. State/Province is not required because not every country uses such subdivisions. Also [the simplest tax provider implementation](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/c6874871f3af517b8507c34e18628d850c60d796/src/Modules/OrchardCore.Commerce/Services/LocalTaxProvider.cs) is made for domestic-only sales in a country with unitary VAT code (applies to a lot of smaller countries), so it all makes sense.

The design philosophy here is to try to make less constraints, less assumptions wherever something is not certain. OrchardCore.Commerce is meant to be a platform, not a turnkey solution, so we try to leave things default and let the website developer override them, when possible. (This goal is not always respected, but it's the general ideal.)

In your case, you can simply add
```csharp
AddressFieldDisplayDriver.RequiredFields[nameof(Address.Province)] = address => address.Province;
```
in your module's Startup.cs or in your web app's Program.cs. Also you may have to override the _AddressFieldEditor_ shape to add the `required="true"` attribute [to the province `InputRow`](https://github.com/OrchardCMS/OrchardCore.Commerce/blob/c6874871f3af517b8507c34e18628d850c60d796/src/Modules/OrchardCore.Commerce.ContentFields/Views/AddressFieldEditor.cshtml#L36).

**Comment by infofromca** [comment]
But the current system use Stripe, as I tested , if we the user do not provide even Country, It did not work by Stripe.

**Comment by sarahelsaig** [comment]
You don't have to use Stripe, it's just option. Also country/region (not province) is always provided with the default address editor anyway, because it's rendered with a drop-down that doesn't have an empty option. So making it required does nothing unless you change the editor.
